# Generated by Django 6.0.6 on 2026-06-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.TextField(max_length=250),
        ),
    ]
